apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- cert-manager
- cloudflared
- crossplane
- external-secrets
- gateway
- cilium
- victoriametrics
- victorialogs
- descheduler
- dex