apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: stalwart-postgresql
  labels:
    app.kubernetes.io/name: cloudnative-pg
    app.kubernetes.io/instance: stalwart-postgresql
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: stalwart-postgresql
  podMetricsEndpoints:
    - port: metrics
