apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: mastodon-sidekiq-scheduler-pdb
  namespace: mastodon
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: mastodon-sidekiq-scheduler
