---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane-job-writer
  labels:
    app.kubernetes.io/name: crossplane
    app.kubernetes.io/component: composition
rules:
  - apiGroups: ["batch"]
    resources: ["jobs", "jobs/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crossplane-job-writer
  labels:
    app.kubernetes.io/name: crossplane
    app.kubernetes.io/component: composition
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crossplane-job-writer
subjects:
  - kind: ServiceAccount
    name: crossplane
    namespace: crossplane-system
