apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - external-secret-mail-dns.yaml
  - cloudflare-serviceaccount.yaml
  - provider-config-cloudflare.yaml
  - provider-config-hcloud.yaml
