apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - project.yaml
  - cryptpad/overlays/prod
  - hypebot/overlays/prod
  - mastodon/overlays/prod
  - elastic/overlays/prod
  - mail/overlays/prod
  - mail/cnpg/overlays/prod
