apiVersion: cilium.io/v2alpha1
kind: CiliumLoadBalancerIPPool
metadata:
  name: mail-public-pool
  namespace: kube-system
spec:
  blocks:
    - start: 95.216.181.4
      stop: 95.216.181.4
  serviceSelector:
    matchLabels:
      app.kubernetes.io/name: stalwart
