---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: database-backup
spec:
  # Daily full base backup at 06:00 UTC.
  # Cron format: minute hour day-of-month month day-of-week
  # "0 6 * * *" = 06:00 every day
  schedule: "0 6 * * *"
  backupOwnerReference: self
  cluster:
    name: database-cnpg
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
    parameters:
      barmanObjectName: database-backup
