apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: stalwart-tls
spec:
  secretName: stalwart-tls
  issuerRef:
    kind: ClusterIssuer
    name: cloudflare-issuer
  dnsNames:
    - mail.peekoff.com
    - smtp.peekoff.com
    - imap.peekoff.com
  usages:
    - digital signature
    - key encipherment
    - server auth
  duration: 2160h
  renewBefore: 720h
