apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stalwart-secret

spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-backend
    kind: ClusterSecretStore
  target:
    name: stalwart-secret
    creationPolicy: Owner
  data:
    - secretKey: ADMIN_PASSWORD
      remoteRef:
        key: app-stalwart-admin-password
