apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: stalwart-autodiscover
spec:
  parentRefs:
    - name: external
      namespace: gateway
  hostnames:
    - "autoconfig.peekoff.com"
    - "autodiscover.peekoff.com"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: stalwart
          namespace: stalwart
          port: 8080
