apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificate.yaml
  - external-secret.yaml
  - httproute-ui.yaml
  - pvc.yaml
  - priorityclasses.yaml
  - resources/
  - service.yaml
  - service-headless.yaml
  - service-mail.yaml
  - statefulset.yaml
