apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: stalwartlabs/stalwart
resources:
  - database.yaml
  - external-secret.yaml
  - http-route.yaml
  - http-route-admin.yaml
  - priorityclasses.yaml
  - pvc.yaml
  - service.yaml
  - service-mail.yaml
  - statefulset.yaml
