apiVersion: v1
kind: Service
metadata:
  name: stalwart-headless
  labels:
    app.kubernetes.io/name: stalwart
    app.kubernetes.io/part-of: stalwart
    app.kubernetes.io/component: mail-server
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: stalwart
  ports:
    - name: client
      port: 8080
      targetPort: 8080
      protocol: TCP
