apiVersion: v1
kind: Service
metadata:
  name: stalwart-mail
  labels:
    app.kubernetes.io/name: stalwart
spec:
  selector:
    app.kubernetes.io/name: stalwart
  ports:
    - name: smtp
      protocol: TCP
      port: 25
      targetPort: 25
      nodePort: 30025
    - name: submission
      protocol: TCP
      port: 587
      targetPort: 587
      nodePort: 30587
    - name: smtps
      protocol: TCP
      port: 465
      targetPort: 465
      nodePort: 30465
    - name: imap
      protocol: TCP
      port: 143
      targetPort: 143
      nodePort: 30143
    - name: imaps
      protocol: TCP
      port: 993
      targetPort: 993
      nodePort: 30993
    - name: pop3
      protocol: TCP
      port: 110
      targetPort: 110
      nodePort: 30110
    - name: pop3s
      protocol: TCP
      port: 995
      targetPort: 995
      nodePort: 30995
  type: NodePort
  externalTrafficPolicy: Local
