apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stalwart
spec:
  template:
    spec:
      containers:
        - name: stalwart
          env:
            - name: HOSTNAME
              value: "mail.peekoff.com"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: stalwart-admin
spec:
  hostnames:
    - "mail.peekoff.com"
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: stalwart-admin-interface
spec:
  hostnames:
    - "mailadmin.peekoff.com"
