apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stalwart

images:
  - name: stalwartlabs/stalwart
    newTag: v0.15.1

resources:
  - ../../base
  - configmap.yaml
  - objectstore.yaml

patches:
  - path: patches/hostnames.yaml
  - path: patches/storageclass.yaml
