apiVersion: meta.pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-go-templating
  namespace: crossplane-system
spec:
  package: xpkg.upbound.io/crossplane-contrib/function-go-templating:v0.8.0
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 3
