apiVersion: pkg.crossplane.io/v1beta1
kind: Function
metadata:
  name: function-pt
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
spec:
  package: xpkg.upbound.io/upbound/function-k8s-pt:v0.2.0
  runtimeConfigRef:
    name: pt-config
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: pt-config
spec: {}