apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-cloudflare
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-cloudflare:v0.40.0
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 3
