apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: stalwart-blob-s3
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-backend
    kind: ClusterSecretStore
  target:
    name: stalwart-blob-s3
    creationPolicy: Owner
  data:
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: app-stalwart-blob-s3-access-key-id
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: app-stalwart-blob-s3-secret-access-key
