apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crossplane-system

resources:
  - namespace.yaml
  - resource-quota.yaml
  - configs/
  - compositions/
  - instances/

helmCharts:
  - name: crossplane
    repo: https://charts.crossplane.io/stable
    version: 1.17.2
    releaseName: crossplane
    namespace: crossplane-system
    valuesFile: values.yaml
