apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: crossplane-system

resources:
  - namespace.yaml
  - resource-quota.yaml
  - install/
  - providers/
  - functions/
  - compositions/
  - instances/
