replicas: 1
deploymentStrategy: Recreate

args:
  - --enable-environment-configs
  - --enable-composition-functions
  - --enable-usages

resourcesCrossplane:
  limits:
    cpu: 200m
    memory: 512Mi
  requests:
    cpu: 50m
    memory: 256Mi

rbacManager:
  deploy: true
  replicas: 1
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 20m
      memory: 128Mi

webhooks:
  enabled: true

metrics:
  enabled: true

provider:
  packages:
    - xpkg.upbound.io/crossplane-contrib/provider-kubernetes:v0.14.1

# PodSecurity restricted:latest compliance
podSecurityContextCrossplane:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
securityContextCrossplane:
  runAsUser: 65532
  runAsGroup: 65532
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

podSecurityContextRBACManager:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
securityContextRBACManager:
  runAsUser: 65532
  runAsGroup: 65532
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
