apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: stalwart-postgresql
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18
  storage:
    size: 50Gi
  walStorage:
    size: 10Gi
  postgresql:
    parameters:
      shared_preload_libraries: "passwordcheck"
  bootstrap:
    initdb:
      database: stalwart
      owner: stalwart
      secret:
        name: stalwart-postgresql-app
  enableSuperuserAccess: false
  monitoring:
    enablePodMonitor: true
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: stalwart-cnpg-backup
