# Override node affinity to allow scheduling on autoscaler nodes
# This overrides any mutating webhook that adds autoscaler-node: DoesNotExist
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-sidekiq-default
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: Exists  # Match all nodes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-sidekiq-federation
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: Exists  # Match all nodes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-sidekiq-background
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: Exists  # Match all nodes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-sidekiq-scheduler
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: Exists  # Match all nodes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-streaming
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: Exists  # Match all nodes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-web
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: Exists  # Match all nodes
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mastodon-redis-master
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: Exists  # Match all nodes
