apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-mail
  namespace: gateway
spec:
  dnsNames:
    - "*.peekoff.com"
    - peekoff.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: cloudflare-issuer
  secretName: cert-mail
  usages:
    - digital signature
    - key encipherment
