apiVersion: apps/v1
kind: Deployment
metadata:
  name: tor-proxy
  namespace: mastodon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tor-proxy
  template:
    metadata:
      labels:
        app: tor-proxy
    spec:
      tolerations:
        - key: "autoscaler-node"
          operator: "Equal"
          value: "true"
          effect: "NoSchedule"
      containers:
        - name: proxy
          image: ghcr.io/avpnusr/torprivoxy:25-10-2025
          ports:
            - containerPort: 8118
              name: http
            - containerPort: 9050
              name: socks
          readinessProbe:
            tcpSocket:
              port: 8118
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8118
            periodSeconds: 30
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 10m
              memory: 64Mi
