apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-web
spec:
  template:
    spec:
      containers:
      - name: web
        env:
        - name: ES_PASS
          valueFrom:
            secretKeyRef:
              name: elasticsearch-es-elastic-user
              key: elastic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-sidekiq-default
spec:
  template:
    spec:
      containers:
      - name: sidekiq-default
        env:
        - name: ES_PASS
          valueFrom:
            secretKeyRef:
              name: elasticsearch-es-elastic-user
              key: elastic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-sidekiq-federation
spec:
  template:
    spec:
      containers:
      - name: sidekiq-federation
        env:
        - name: ES_PASS
          valueFrom:
            secretKeyRef:
              name: elasticsearch-es-elastic-user
              key: elastic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-sidekiq-background
spec:
  template:
    spec:
      containers:
      - name: sidekiq-background
        env:
        - name: ES_PASS
          valueFrom:
            secretKeyRef:
              name: elasticsearch-es-elastic-user
              key: elastic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-sidekiq-scheduler
spec:
  template:
    spec:
      containers:
      - name: sidekiq-scheduler
        env:
        - name: ES_PASS
          valueFrom:
            secretKeyRef:
              name: elasticsearch-es-elastic-user
              key: elastic
