# Production resource requests and limits
# These values are tuned for production workload and traffic
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-web
spec:
  template:
    spec:
      containers:
        - name: web
          resources:
            requests:
              cpu: "683m"
              memory: "2271Mi"
            limits:
              memory: "2750Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-streaming
spec:
  template:
    spec:
      containers:
        - name: streaming
          resources:
            requests:
              cpu: "21m"
              memory: "100Mi"
            limits:
              memory: "100Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-sidekiq-default
spec:
  template:
    spec:
      containers:
        - name: sidekiq-default
          resources:
            requests:
              cpu: "500m"
              memory: "800Mi"
            limits:
              memory: "1.2Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-sidekiq-federation
spec:
  template:
    spec:
      containers:
        - name: sidekiq-federation
          resources:
            requests:
              cpu: "400m"
              memory: "1Gi"
            limits:
              memory: "1.5Gi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-sidekiq-background
spec:
  template:
    spec:
      containers:
        - name: sidekiq-background
          resources:
            requests:
              cpu: "200m"
              memory: "500Mi"
            limits:
              memory: "800Mi"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mastodon-sidekiq-scheduler
spec:
  template:
    spec:
      containers:
        - name: sidekiq-scheduler
          resources:
            requests:
              cpu: "100m"
              memory: "300Mi"
            limits:
              memory: "500Mi"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mastodon-redis-master
spec:
  template:
    spec:
      containers:
        - name: redis
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: database-cnpg
spec:
  instances: 2
  storage:
    size: 80Gi
  walStorage:
    size: 20Gi
  resources:
    requests:
      memory: "2Gi"
      cpu: "1"
    limits:
      memory: "2Gi"
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: database-cnpg-pooler-rw
spec:
  instances: 2
---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: database-cnpg-pooler-ro
spec:
  instances: 2
